Repository ansible/event-driven-ansible, pull requests merged in 2024-11, with the labels that each got.

#350 feat: optionally check if all env vars match
  extensions/eda/plugins/event_source/generic.py
  tests/unit/event_source/test_generic.py
Labels: enhancement, feature

#352 fix: ensure mandatory params for activation
  plugins/module_utils/common.py
  plugins/modules/rulebook_activation.py
  tests/integration/targets/activation/tasks/main.yml
Labels: bug

#355 ci: make publication only run with tags
  .github/workflows/tox.yml
Labels: bug

#357 ci: pin tox-extra version
  tox.ini
Labels: skip-changelog
