Repository ansible/event-driven-ansible, pull requests merged in 2024-08, with the labels that each got.

#218 test: fix pre-commit reported issues
  .gitleaks.toml
  .pre-commit-config.yaml
  extensions/eda/rulebooks/demo_rulebook.yml
  tox.ini
Labels: skip-changelog

#217 chore: fix spellcheck errors and enable cspell
  .config/dictionary.txt
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .pre-commit-config.yaml
  cspell.config.yaml
  extensions/eda/plugins/event_filter/insert_hosts_to_meta.py
  extensions/eda/plugins/event_filter/normalize_keys.py
  extensions/eda/plugins/event_source/aws_cloudtrail.py
  extensions/eda/plugins/event_source/aws_sqs_queue.py
  extensions/eda/plugins/event_source/generic.py
  extensions/eda/plugins/event_source/pg_listener.py
  plugins/modules/upcase.py
  requirements.txt
  tests/integration/event_source_kafka/certs-create.sh
  tests/integration/event_source_url_check/test_url_check_source.py
Labels: bug

#220 chore: enable release-drafter
  .github/release-drafter.yml
  .github/workflows/ack.yml
  .github/workflows/push.yml
Labels: skip-changelog

#221 Upgrade linters and refactor how they run
  .config/dictionary.txt
  .github/workflows/ack.yml
  .github/workflows/linters.yml
  .isort.cfg
  .pre-commit-config.yaml
  extensions/eda/plugins/event_filter/insert_hosts_to_meta.py
  extensions/eda/plugins/event_source/journald.py
  extensions/eda/plugins/event_source/webhook.py
  lint_requirements.txt
  pyproject.toml
  test_requirements.txt
  tox.ini
Labels: bug

#223 Unify testing jobs into a single workflows
  .github/workflows/integration-tests.yml
  .github/workflows/tests.yml
  .github/workflows/tox.yml
  CONTRIBUTING.md
  requirements.txt
  test_requirements.txt
  tox.ini
Labels: skip-changelog

#224 Enable testing with python 3.11 and 3.12
  .github/workflows/tox.yml
Labels: skip-changelog

#225 Correct psycopg requirements
  .github/workflows/tox.yml
  requirements.txt
  tests/unit/requirements.txt
  tox.ini
Labels: bug

#228 Ensure we use ubuntu 24.04 runners for testing
  .github/workflows/tox.yml
Labels: skip-changelog

#231 Fix ack/push workflows on GHA
  .github/workflows/ack.yml
  .github/workflows/push.yml
Labels: skip-changelog

#233 Install docker-compose v2 on ubuntu
  .config/dictionary.txt
  .github/workflows/tox.yml
  tests/integration/event_source_kafka/test_kafka_source.py
  tox.ini
Labels: skip-changelog

#235 Update pre-commit config
  .pre-commit-config.yaml
Labels: skip-changelog

#236 Correct requirements and update docs
  README.md
  demos/dynatrace-demo/instructions.md
  meta/runtime.yml
  requirements.txt
  test_requirements.txt
Labels: bug

#239 Add bindep file for testing system dependencies
  .config/dictionary.txt
  .github/workflows/tox.yml
  bindep.txt
  tox.ini
Labels: skip-changelog

#242 Ignore common linting rules
  .config/dictionary.txt
  .pre-commit-config.yaml
Labels: enhancement

#241 Run sanity with all supported python versions
  .github/workflows/tox.yml
  bindep.txt
  tox.ini
Labels: skip-changelog

#243 Add support for python 3.12
  .github/workflows/tox.yml
  requirements.txt
Labels: bug

#245 Chain tests specific to a python-platform into single jobs
  .github/workflows/tox.yml
  tox.ini
Labels: skip-changelog

#244 Add module_utils
  .pre-commit-config.yaml
  plugins/doc_fragments/__init__.py
  plugins/doc_fragments/eda_controller.py
  plugins/module_utils/__init__.py
  plugins/module_utils/arguments.py
  plugins/module_utils/client.py
  plugins/module_utils/controller.py
  plugins/module_utils/errors.py
  plugins/modules/__init__.py
  pyproject.toml
Labels: enhancement

#246 Enable testing with an arm64 linux runner
  .github/workflows/tox.yml
Labels: skip-changelog

#250 Enable coverage collecting and reporting
  .github/workflows/tox.yml
  .gitignore
  codecov.yml
  extensions/eda/plugins/event_source/__init__.py
  pyproject.toml
  test_requirements.txt
  tox.ini
Labels: skip-changelog

#227 Replace unmaintained docker-compose with podman-compose
  CONTRIBUTING.md
  test_requirements.txt
  tests/integration/event_source_kafka/test_kafka_source.py
Labels: skip-changelog

#253 Enable junit.xml reporting
  .github/workflows/tox.yml
  tox.ini
Labels: skip-changelog

#259 Avoid uploading codecov junit when token is missing
  .github/workflows/tox.yml
Labels: skip-changelog

#260 Enable mypy with minimal checks
  .pre-commit-config.yaml
  extensions/eda/plugins/event_source/aws_sqs_queue.py
  extensions/eda/plugins/event_source/webhook.py
  pyproject.toml
Labels: skip-changelog

#261 Address arg-type, return and return-value type errors
  extensions/eda/plugins/event_source/alertmanager.py
  extensions/eda/plugins/event_source/aws_cloudtrail.py
  extensions/eda/plugins/event_source/aws_sqs_queue.py
  extensions/eda/plugins/event_source/azure_service_bus.py
  extensions/eda/plugins/event_source/file_watch.py
  extensions/eda/plugins/event_source/generic.py
  extensions/eda/plugins/event_source/journald.py
  extensions/eda/plugins/event_source/kafka.py
  extensions/eda/plugins/event_source/pg_listener.py
  extensions/eda/plugins/event_source/range.py
  extensions/eda/plugins/event_source/tick.py
  extensions/eda/plugins/event_source/url_check.py
  extensions/eda/plugins/event_source/webhook.py
  pyproject.toml
Labels: bug

#262 Address index, union-attr and misc typing errors
  extensions/eda/plugins/event_source/aws_sqs_queue.py
  extensions/eda/plugins/event_source/journald.py
  pyproject.toml
  tests/integration/event_source_webhook/test_webhook_source.py
Labels: skip-changelog

#263 Address more typing errors
  extensions/eda/plugins/event_source/aws_cloudtrail.py
  extensions/eda/plugins/event_source/aws_sqs_queue.py
  extensions/eda/plugins/event_source/generic.py
  extensions/eda/plugins/event_source/kafka.py
  extensions/eda/plugins/event_source/pg_listener.py
  pyproject.toml
  tests/integration/event_source_url_check/test_url_check_source.py
Labels: skip-changelog

#238 Add project module
  .config/dictionary.txt
  plugins/modules/project.py
  plugins/modules/project_info.py
  tests/integration/targets/project/tasks/create.yml
  tests/integration/targets/project/tasks/delete.yml
  tests/integration/targets/project/tasks/main.yml
  tests/integration/targets/project/tasks/update.yml
  tests/integration/targets/project_info/tasks/create.yml
  tests/integration/targets/project_info/tasks/main.yml
Labels: enhancement

#240 Add credential_type module
  .config/dictionary.txt
  meta/runtime.yml
  plugins/module_utils/common.py
  plugins/modules/credential_type.py
  plugins/modules/credential_type_info.py
  plugins/modules/project.py
  plugins/modules/project_info.py
  tests/integration/targets/credential_type/tasks/main.yml
Labels: enhancement

#248 Add decision environment module
  plugins/modules/decision_environment.py
  plugins/modules/decision_environment_info.py
  tests/integration/targets/decision_environment/tasks/create.yml
  tests/integration/targets/decision_environment/tasks/delete.yml
  tests/integration/targets/decision_environment/tasks/main.yml
  tests/integration/targets/decision_environment/tasks/update.yml
  tests/integration/targets/decision_environment_info/tasks/list.yml
  tests/integration/targets/decision_environment_info/tasks/main.yml
Labels: enhancement

#249 Refactor plugins/module_utils/controller.py for better testing
  .config/dictionary.txt
  plugins/module_utils/controller.py
  pyproject.toml
  tests/unit/plugins/module_utils/test_client.py
  tests/unit/plugins/module_utils/test_controller.py
Labels: bug

#251 Add credential and credential_info modules
  .config/dictionary.txt
  meta/runtime.yml
  plugins/module_utils/controller.py
  plugins/modules/credential.py
  plugins/modules/credential_info.py
  tests/integration/targets/credential/tasks/main.yml
Labels: enhancement

#264 Address more typing errors
  .pre-commit-config.yaml
  extensions/eda/plugins/event_source/aws_cloudtrail.py
  extensions/eda/plugins/event_source/azure_service_bus.py
  extensions/eda/plugins/event_source/file.py
  extensions/eda/plugins/event_source/file_watch.py
  extensions/eda/plugins/event_source/journald.py
  plugins/modules/project_info.py
  pyproject.toml
Labels: skip-changelog

#198 Add schemas for our source plugins
  extensions/eda/plugins/event_source/range_input_schema.json
  extensions/eda/plugins/event_source/range_output_schema.json
  extensions/eda/plugins/event_source/schemas/alertmanager.json
  extensions/eda/plugins/event_source/schemas/aws_cloudtrail.json
  extensions/eda/plugins/event_source/schemas/aws_sqs_queue.json
  extensions/eda/plugins/event_source/schemas/azure_service_bus.json
  extensions/eda/plugins/event_source/schemas/file.json
  extensions/eda/plugins/event_source/schemas/file_watch.json
  extensions/eda/plugins/event_source/schemas/generic.json
  extensions/eda/plugins/event_source/schemas/journald.json
  extensions/eda/plugins/event_source/schemas/kafka.json
  extensions/eda/plugins/event_source/schemas/pg_listener.json
  extensions/eda/plugins/event_source/schemas/range.json
  extensions/eda/plugins/event_source/schemas/url_check.json
  extensions/eda/plugins/event_source/schemas/webhook.json
Labels: enhancement

#237 Update README to match the template
  CONTRIBUTING.md
  README.md
Labels: enhancement

#265 Temporary disable coverage downgrade step inside check job
  .github/workflows/tox.yml
Labels: skip-changelog

#256 Add controller_token module
  plugins/modules/controller_token.py
  tests/integration/targets/controller_token/tasks/create.yml
  tests/integration/targets/controller_token/tasks/main.yml
Labels: enhancement

#254 Add activation and activation_info modules
  .config/dictionary.txt
  meta/runtime.yml
  plugins/modules/activation.py
  plugins/modules/activation_info.py
  tests/integration/targets/activation/tasks/main.yml
Labels: enhancement

#266 Remove test module
  plugins/modules/upcase.py
  roles/test_role/README.md
  roles/test_role/defaults/main.yml
  roles/test_role/handlers/main.yml
  roles/test_role/meta/main.yml
  roles/test_role/tasks/main.yml
  roles/test_role/tests/inventory
  roles/test_role/tests/test.yml
  roles/test_role/vars/main.yml
Labels: bug

#271 Run sanity check after linting
  .github/workflows/tox.yml
  tox.ini
Labels: skip-changelog

#270 Add some critical types to module_utils and fix logic
  plugins/module_utils/arguments.py
  plugins/module_utils/common.py
  plugins/module_utils/controller.py
  plugins/modules/activation.py
  plugins/modules/activation_info.py
  plugins/modules/controller_token.py
  plugins/modules/credential.py
  plugins/modules/credential_info.py
  plugins/modules/credential_type.py
  plugins/modules/credential_type_info.py
  plugins/modules/decision_environment.py
  plugins/modules/decision_environment_info.py
  plugins/modules/project.py
  plugins/modules/project_info.py
  tests/sanity/ignore-2.15.txt
  tests/sanity/ignore-2.16.txt
  tests/sanity/ignore-2.17.txt
  tests/sanity/ignore-2.18.txt
Labels: bug

#276 Add docs building and testing
  .config/dictionary.txt
  .github/workflows/tox.yml
  .gitignore
  .pre-commit-config.yaml
  .readthedocs.yaml
  bindep.txt
  demos/dynatrace-demo/instructions.md
  docs/.gitignore
  docs/bin/README.md
  docs/bin/rsync
  docs/requirements.txt
  docs/rst/activation_info_module.rst
  docs/rst/activation_module.rst
  docs/rst/controller_token_module.rst
  docs/rst/credential_info_module.rst
  docs/rst/credential_module.rst
  docs/rst/credential_type_info_module.rst
  docs/rst/credential_type_module.rst
  docs/rst/decision_environment_info_module.rst
  docs/rst/decision_environment_module.rst
  docs/rst/environment_variables.rst
  docs/rst/index.rst
  docs/rst/project_info_module.rst
  docs/rst/project_module.rst
  docs/rst/user_module.rst
  tox.ini
Labels: bug

#274 Run integration tests in CI
  .config/dictionary.txt
  .github/workflows/integration.yml
  docs/rst/credential_module.rst
  docs/rst/decision_environment_module.rst
  docs/rst/project_module.rst
  meta/runtime.yml
  plugins/module_utils/controller.py
  plugins/modules/activation.py
  plugins/modules/credential.py
  plugins/modules/decision_environment.py
  plugins/modules/project.py
  plugins/modules/project_info.py
  tests/integration/integration_config.yaml.template
  tests/integration/targets/activation/tasks/main.yml
  tests/integration/targets/controller_token/tasks/create.yml
  tests/integration/targets/controller_token/tasks/main.yml
  tests/integration/targets/credential/tasks/main.yml
  tests/integration/targets/credential_type/tasks/main.yml
  tests/integration/targets/decision_environment/tasks/create.yml
  tests/integration/targets/decision_environment/tasks/delete.yml
  tests/integration/targets/decision_environment/tasks/main.yml
  tests/integration/targets/decision_environment/tasks/update.yml
  tests/integration/targets/decision_environment_info/tasks/list.yml
  tests/integration/targets/decision_environment_info/tasks/main.yml
  tests/integration/targets/project/tasks/create.yml
  tests/integration/targets/project/tasks/delete.yml
  tests/integration/targets/project/tasks/main.yml
  tests/integration/targets/project/tasks/update.yml
  tests/integration/targets/project_info/tasks/create.yml
  tests/integration/targets/project_info/tasks/main.yml
  tests/integration/targets/user/tasks/create.yml
  tests/integration/targets/user/tasks/main.yml
  tests/integration/targets/user/tasks/update.yml
  tox.ini
Labels: enhancement

#278 Make docs building logic more resilient
  bindep.txt
  tox.ini
Labels: skip-changelog

#275 Cleanup module_utils and ensure consistence in the code base
  plugins/module_utils/common.py
  plugins/module_utils/controller.py
  plugins/modules/activation.py
  plugins/modules/activation_info.py
  plugins/modules/controller_token.py
  plugins/modules/credential.py
  plugins/modules/credential_info.py
  plugins/modules/credential_type.py
  plugins/modules/credential_type_info.py
  plugins/modules/decision_environment.py
  plugins/modules/decision_environment_info.py
  plugins/modules/project.py
  plugins/modules/project_info.py
  plugins/modules/user.py
  tests/unit/plugins/module_utils/test_common.py
Labels: enhancement

#280 Make sanity jobs use containers
  .github/workflows/tox.yml
  bindep.txt
  tests/config.yml
  tests/sanity/ignore-2.15.txt
  tests/sanity/ignore-2.16.txt
  tests/sanity/ignore-2.17.txt
  tox.ini
Labels: skip-changelog

#279 Consolidate new integration tests into tox workflow as staging job
  .github/workflows/integration.yml
  .github/workflows/tox.yml
  .gitignore
  tests/run-staging
  tox.ini
Labels: skip-changelog

#284 Update anstibull-docs
  .gitignore
  docs/.gitignore
  docs/requirements.txt
  docs/rst/activation_info_module.rst
  docs/rst/activation_module.rst
  docs/rst/controller_token_module.rst
  docs/rst/credential_info_module.rst
  docs/rst/credential_module.rst
  docs/rst/credential_type_info_module.rst
  docs/rst/credential_type_module.rst
  docs/rst/decision_environment_info_module.rst
  docs/rst/decision_environment_module.rst
  docs/rst/environment_variables.rst
  docs/rst/index.rst
  docs/rst/project_info_module.rst
  docs/rst/project_module.rst
  docs/rst/user_module.rst
Labels: bug

#286 Ensure that mypy results are consistent
  .pre-commit-config.yaml
  extensions/eda/plugins/event_source/file.py
  extensions/eda/plugins/event_source/file_watch.py
Labels: bug

#285 Untrack antsibull-docs generated files
  .config/dictionary.txt
  .config/requirements-docs.txt
  .gitignore
  .pre-commit-config.yaml
  docs/.gitignore
  docs/requirements.txt
  docs/rst/activation_info_module.rst
  docs/rst/activation_module.rst
  docs/rst/controller_token_module.rst
  docs/rst/credential_info_module.rst
  docs/rst/credential_module.rst
  docs/rst/credential_type_info_module.rst
  docs/rst/credential_type_module.rst
  docs/rst/decision_environment_info_module.rst
  docs/rst/decision_environment_module.rst
  docs/rst/environment_variables.rst
  docs/rst/index.rst
  docs/rst/project_info_module.rst
  docs/rst/project_module.rst
  docs/rst/user_module.rst
  tox.ini
Labels: bug

#282 Add more types
  plugins/module_utils/client.py
  plugins/module_utils/common.py
  plugins/module_utils/controller.py
  plugins/modules/activation.py
  plugins/modules/controller_token.py
  plugins/modules/user.py
  tests/conftest.py
  tests/integration/conftest.py
  tests/integration/event_source_kafka/test_kafka_source.py
  tests/integration/event_source_url_check/test_url_check_source.py
  tests/integration/event_source_webhook/test_webhook_source.py
  tests/integration/utils.py
  tests/unit/event_filter/test_insert_hosts_to_meta.py
  tests/unit/event_filter/test_normalize_keys.py
  tests/unit/event_source/test_alertmanager.py
  tests/unit/event_source/test_aws_cloudtrail.py
  tests/unit/event_source/test_aws_sqs_queue.py
  tests/unit/event_source/test_azure_service_bus.py
  tests/unit/event_source/test_generic.py
  tests/unit/event_source/test_kafka.py
  tests/unit/event_source/test_pg_listener.py
  tests/unit/event_source/test_webhook.py
  tests/unit/plugins/module_utils/test_client.py
  tests/unit/plugins/module_utils/test_common.py
  tests/unit/plugins/module_utils/test_controller.py
Labels: bug

#281 Add support for AAP 2.4
  plugins/modules/activation.py
  plugins/modules/credential.py
  plugins/modules/credential_info.py
  plugins/modules/credential_type.py
  plugins/modules/credential_type_info.py
  plugins/modules/decision_environment.py
  plugins/modules/project.py
  plugins/modules/user.py
Labels: enhancement

#287 types: address disallow_untyped_defs for tests/
  extensions/eda/plugins/event_source/file.py
  extensions/eda/plugins/event_source/file_watch.py
  pyproject.toml
  tests/conftest.py
  tests/integration/conftest.py
  tests/integration/event_source_kafka/test_kafka_source.py
  tests/integration/event_source_url_check/test_url_check_source.py
  tests/integration/event_source_webhook/test_webhook_source.py
  tests/integration/utils.py
  tests/unit/event_filter/test_insert_hosts_to_meta.py
  tests/unit/event_filter/test_normalize_keys.py
  tests/unit/event_source/test_alertmanager.py
  tests/unit/event_source/test_aws_cloudtrail.py
  tests/unit/event_source/test_aws_sqs_queue.py
  tests/unit/event_source/test_azure_service_bus.py
  tests/unit/event_source/test_generic.py
  tests/unit/event_source/test_kafka.py
  tests/unit/event_source/test_pg_listener.py
  tests/unit/event_source/test_webhook.py
  tests/unit/plugins/module_utils/test_client.py
  tests/unit/plugins/module_utils/test_controller.py
Labels: skip-changelog

#230 Enable changelogs for collection
  .gitignore
  .pre-commit-config.yaml
  changelogs/changelog.yaml
  changelogs/config.yaml
  changelogs/fragments/.gitkeep
  cspell.config.yaml
  tox.ini
Labels: enhancement

#289 type: address disallow_untyped_defs
  extensions/eda/plugins/event_source/file.py
  plugins/module_utils/client.py
  plugins/module_utils/controller.py
  pyproject.toml
  tests/unit/plugins/module_utils/test_controller.py
Labels: skip-changelog

#290 type: make code respect mypy strict mode
  .pre-commit-config.yaml
  extensions/eda/plugins/event_filter/dashes_to_underscores.py
  extensions/eda/plugins/event_filter/json_filter.py
  extensions/eda/plugins/event_filter/noop.py
  extensions/eda/plugins/event_filter/normalize_keys.py
  extensions/eda/plugins/event_source/alertmanager.py
  extensions/eda/plugins/event_source/aws_cloudtrail.py
  extensions/eda/plugins/event_source/aws_sqs_queue.py
  extensions/eda/plugins/event_source/azure_service_bus.py
  extensions/eda/plugins/event_source/file.py
  extensions/eda/plugins/event_source/file_watch.py
  extensions/eda/plugins/event_source/generic.py
  extensions/eda/plugins/event_source/journald.py
  extensions/eda/plugins/event_source/kafka.py
  extensions/eda/plugins/event_source/pg_listener.py
  extensions/eda/plugins/event_source/range.py
  extensions/eda/plugins/event_source/tick.py
  extensions/eda/plugins/event_source/url_check.py
  extensions/eda/plugins/event_source/webhook.py
  plugins/module_utils/controller.py
  pyproject.toml
  requirements.txt
  tests/integration/conftest.py
  tests/integration/event_source_kafka/test_kafka_source.py
  tests/integration/event_source_url_check/test_url_check_source.py
  tests/integration/event_source_webhook/test_webhook_source.py
  tests/integration/utils.py
  tests/unit/event_filter/test_insert_hosts_to_meta.py
  tests/unit/event_filter/test_normalize_keys.py
  tests/unit/event_source/test_alertmanager.py
  tests/unit/event_source/test_azure_service_bus.py
  tests/unit/event_source/test_generic.py
  tests/unit/event_source/test_kafka.py
  tests/unit/event_source/test_pg_listener.py
  tests/unit/event_source/test_webhook.py
Labels: skip-changelog

#291 Test collection building
  .ansible-lint
  .config/README.md
  .config/dictionary.txt
  .config/galaxy-importer.cfg
  .config/manifest.txt
  .gitignore
  .pre-commit-config.yaml
  continuous_integration.yml
  galaxy.yml
  run_pytest.yml
  start_app.yml
  tests/run-galaxy-importer
  tests/sanity/ignore-2.15.txt
  tests/sanity/ignore-2.16.txt
  tests/sanity/ignore-2.17.txt
  tests/sanity/ignore-2.18.txt
Labels: skip-changelog

#293 fix: raise OperationalError and Decoding Errors
  extensions/eda/plugins/event_source/pg_listener.py
  tests/unit/event_source/test_pg_listener.py
Labels: bug

#294 Fix CHANGELOG reference path into README
  README.md
Labels: bug, documentation
