Repository ansible/event-driven-ansible, pull requests merged in 2024-09, with the labels that each got.

#297 Integrate antibull-changelog
  .config/dictionary.txt
  .config/manifest.txt
  .gitignore
  .pre-commit-config.yaml
  .readthedocs.yaml
  CHANGELOG.md
  README.md
  changelogs/changelog.yaml
  changelogs/config.yaml
  changelogs/fragments/297-bug.yaml
  cspell.config.yaml
  docs/bin/README.md
  docs/bin/rsync
  docs/docsite/config.yml
  docs/docsite/extra-docs.yml
  galaxy.yml
  tests/run-docs
  tests/run-galaxy-importer
  tox.ini
Labels: bug

#300 Generate CHANGELOG.md using github release-drafter
  .config/constraints.txt
  .config/manifest.txt
  .config/requirements-docs.txt
  .github/workflows/tox.yml
  .gitignore
  .pre-commit-config.yaml
  .readthedocs.yaml
  .tool-versions
  changelogs/changelog.yaml
  changelogs/config.yaml
  changelogs/fragments/.gitkeep
  changelogs/fragments/297-bug.yaml
  docs/.changelog.yml
  docs/.gitignore
  docs/antsibull-docs.cfg
  docs/build.sh
  docs/conf.py
  docs/docsite/extra-docs.yml
  docs/docsite/links.yml
  galaxy.yml
  tests/run-docs
  tests/run-galaxy-importer
  tox.ini
Labels: bug

#302 gha: restore testing piplines
  .github/workflows/tox.yml
Labels: skip-changelog

#303 Ensure we use pre-release versions with untagged commits
  .config/constraints.txt
  .config/manifest.txt
  .config/requirements-docs.txt
  .github/workflows/tox.yml
  docs/build.sh
  tests/run-galaxy-importer
  tox.ini
Labels: skip-changelog

#304 Add code for publishing to galaxy.ansible.com on release
  .github/dependabot.yml
  .github/workflows/tox.yml
Labels: skip-changelog

#308 Tell dependabot to not update bleach
  .github/dependabot.yml
Labels: skip-changelog

#311 docs: fix CONTROLLER_HOST environment variable
  plugins/doc_fragments/eda_controller.py
Labels: bug

#314 Refactor docs building and make changelog visible in web interface
  .config/README.md
  .config/dictionary.txt
  .config/manifest.txt
  .config/requirements-docs.in
  .config/requirements-test.in
  .config/requirements-test.txt
  .config/requirements.in
  .github/dependabot.yml
  .gitignore
  .readthedocs.yaml
  CONTRIBUTING.md
  docs/build.sh
  galaxy.yml
  tox.ini
Labels: bug

#317 chore: add example playbook for basic setup
  .config/manifest.txt
  examples/eda-setup.yml
Labels: skip-changelog

#322 fix: update log_level and restart_policy default values
  plugins/modules/activation.py
Labels: bug

#316 activation - rename webhooks option to event_streams and add rulebook_info module
  .config/dictionary.txt
  .config/manifest.txt
  meta/runtime.yml
  plugins/modules/activation.py
  plugins/modules/activation_info.py
  plugins/modules/rulebook_info.py
  tests/integration/targets/activation/tasks/main.yml
Labels: bug

#325 fix: ensure correct required params for event streams
  plugins/modules/event_stream.py
  tests/integration/targets/activation/tasks/main.yml
  tests/integration/targets/event_stream/tasks/main.yml
Labels: bug

#321 event_stream - add support for headers and forward_events options
  plugins/modules/event_stream.py
  tests/integration/targets/event_stream/tasks/main.yml
Labels: enhancement

#318 Rename activation and activation_info modules
  .config/manifest.txt
  README.md
  meta/runtime.yml
  plugins/modules/rulebook_activation.py
  plugins/modules/rulebook_activation_info.py
  tests/integration/targets/activation/tasks/main.yml
Labels: enhancement

#326 chore: bump 2.1.0
  galaxy.yml
Labels: skip-changelog

#328 chore: fix lint issues and include tests config in collection tarball
  .config/manifest.txt
  examples/eda-setup.yml
  galaxy.yml
  meta/runtime.yml
  plugins/modules/credential_info.py
  plugins/modules/credential_type.py
  plugins/modules/credential_type_info.py
  plugins/modules/event_stream_info.py
  plugins/modules/rulebook_activation.py
  plugins/modules/rulebook_activation_info.py
  plugins/modules/rulebook_info.py
  plugins/modules/user.py
Labels: skip-changelog

#330 Corrected GHA publish condition
  .github/workflows/tox.yml
Labels: skip-changelog
