Repository ansible/event-driven-ansible, pull requests merged in 2025-01, with the labels that each got.

#379 chore: remove docker
  tests/integration/event_source_kafka/docker-compose.yml
Labels: skip-changelog

#381 fix: [AAP-38952] incorrect 'image_url' in tests
  tests/integration/targets/decision_environment/tasks/main.yml
  tests/integration/targets/decision_environment_info/tasks/main.yml
Labels: bug

#382 Bump version to 2.3.1
  galaxy.yml
Labels: skip-changelog

#383 feat: support kwargs for pg conn in pg_listener
  extensions/eda/plugins/event_source/pg_listener.py
  tests/unit/event_source/test_pg_listener.py
Labels: enhancement

#386 Bump version to 2.4.0
  galaxy.yml
Labels: skip-changelog
