Repository ansible/event-driven-ansible, pull requests merged in 2025-02, with the labels that each got.

#388 feat: [AAP-38755] add documentation for event filter plugins
  .config/dictionary.txt
  extensions/eda/plugins/event_filter/dashes_to_underscores.py
  extensions/eda/plugins/event_filter/insert_hosts_to_meta.py
  extensions/eda/plugins/event_filter/json_filter.py
  extensions/eda/plugins/event_filter/noop.py
  extensions/eda/plugins/event_filter/normalize_keys.py
Labels: enhancement, feature

#389 feat: [AAP-38755] add documentation for alertmanager, aws_cloudtrail and aws_sqs_queue plugins
  .config/dictionary.txt
  extensions/eda/plugins/event_filter/dashes_to_underscores.py
  extensions/eda/plugins/event_filter/insert_hosts_to_meta.py
  extensions/eda/plugins/event_filter/json_filter.py
  extensions/eda/plugins/event_filter/noop.py
  extensions/eda/plugins/event_filter/normalize_keys.py
  extensions/eda/plugins/event_source/alertmanager.py
  extensions/eda/plugins/event_source/aws_cloudtrail.py
  extensions/eda/plugins/event_source/aws_sqs_queue.py
Labels: enhancement, feature

#390 feat: [AAP-38755] add documentation for azure_service_bus, file and file_watch plugins
  extensions/eda/plugins/event_source/azure_service_bus.py
  extensions/eda/plugins/event_source/file.py
  extensions/eda/plugins/event_source/file_watch.py
Labels: enhancement, feature

#391 feat: [AAP-38755] add documentation for generic, journald and kafka plugins
  extensions/eda/plugins/event_source/generic.py
  extensions/eda/plugins/event_source/journald.py
  extensions/eda/plugins/event_source/kafka.py
Labels: enhancement, feature

#395 bump version to 2.5.0
  galaxy.yml
Labels: skip-changelog

#402 Fix YAML syntax issues in DOCUMENTATION
  extensions/eda/plugins/event_source/aws_cloudtrail.py
  extensions/eda/plugins/event_source/aws_sqs_queue.py
  extensions/eda/plugins/event_source/pg_listener.py
Labels: documentation

#400 feat [AAP-37306]: add support for copy activations
  .config/dictionary.txt
  plugins/module_utils/controller.py
  plugins/modules/rulebook_activation.py
  tests/integration/targets/activation/tasks/main.yml
Labels: enhancement, feature

#399 feat: [AAP-37428] add support for copy credential
  plugins/modules/credential.py
  tests/integration/targets/credential/tasks/main.yml
Labels: enhancement, feature
