Repository ansible/event-driven-ansible, pull requests merged in 2025-05, with the labels that each got.

#364 ADD scm_branch to project module
  .config/dictionary.txt
  plugins/modules/project.py
  tests/integration/targets/project/tasks/main.yml
  tests/integration/targets/project/tasks/scm_branch.yml
Labels: enhancement

#428 fix: remove duplicates and update mismatched python versions in tox.yml
  .github/workflows/tox.yml
Labels: bug

#430 chore: release 2.8.0
  galaxy.yml
Labels: skip-changelog

#433 tests: generate certs at test time using sscg
  .config/dictionary.txt
  .github/workflows/tox.yml
  .gitleaks.toml
  tests/unit/event_source/certs/client.crt
  tests/unit/event_source/certs/client.key
  tests/unit/event_source/certs/server.crt
  tests/unit/event_source/certs/server.key
  tests/unit/event_source/test_webhook.py
Labels: skip-changelog

#434 chore: fix the dependabot configuration
  .github/dependabot.yml
Labels: skip-changelog

#437 update config
  .github/workflows/tox.yml
Labels: skip-changelog

#432 fix: really check all the URLs in url_check
  extensions/eda/plugins/event_source/url_check.py
  tests/integration/event_source_url_check/test_url_check_rules_urls.yml
  tests/integration/event_source_url_check/test_url_check_source.py
Labels: bug

#436 chore: disable pylint too-many-positional-arguments
  pyproject.toml
Labels: skip-changelog

#429 chore: add ruff to github workflow
  .github/workflows/tox.yml
  extensions/eda/plugins/event_filter/dashes_to_underscores.py
  extensions/eda/plugins/event_filter/insert_hosts_to_meta.py
  extensions/eda/plugins/event_filter/json_filter.py
  extensions/eda/plugins/event_filter/normalize_keys.py
  extensions/eda/plugins/event_source/aws_cloudtrail.py
  extensions/eda/plugins/event_source/aws_sqs_queue.py
  extensions/eda/plugins/event_source/file.py
  extensions/eda/plugins/event_source/file_watch.py
  extensions/eda/plugins/event_source/generic.py
  extensions/eda/plugins/event_source/journald.py
  extensions/eda/plugins/event_source/kafka.py
  extensions/eda/plugins/event_source/pg_listener.py
  extensions/eda/plugins/event_source/url_check.py
  extensions/eda/plugins/event_source/webhook.py
  tests/unit/event_source/test_aws_cloudtrail.py
  tox.ini
Labels: skip-changelog

#439 fix: [AAP-41454] adjust project url edit test
  tests/integration/targets/project/tasks/update.yml
Labels: bug

#438 sanitize hostname URL with startswith validation
  plugins/module_utils/client.py
  tests/unit/plugins/module_utils/test_client.py
Labels: bug
