Repository ansible/event-driven-ansible, pull requests merged in 2025-04, with the labels that each got.

#419 fix: [AAP-42971] fix syntax issues in event source plugins
  extensions/eda/plugins/event_source/alertmanager.py
  extensions/eda/plugins/event_source/webhook.py
Labels: bug

#421 fix: pass in optional arguments to sqs
  extensions/eda/plugins/event_source/aws_sqs_queue.py
  tests/unit/event_source/test_aws_sqs_queue.py
Labels: enhancement

#423 chore: release 2.7.0
  galaxy.yml
Labels: skip-changelog

#427 fix: update links in README
  README.md
  galaxy.yml
Labels: bug
