Repository ansible/event-driven-ansible, pull requests merged in 2025-03, with the labels that each got.

#403 chore: release 2.6
  galaxy.yml
  plugins/modules/credential.py
  plugins/modules/rulebook_activation.py
Labels: skip-changelog

#398 fix: add support for Kafka GSSAPI
  .config/dictionary.txt
  .github/workflows/tox.yml
  extensions/eda/plugins/event_source/kafka.py
  requirements.txt
  tests/unit/requirements.txt
  tox.ini
Labels: enhancement

#412 docs: fix outdated ansible-rulebook docs link
  CONTRIBUTING.md
  README.md
Labels: bug

#413 Add Platform Authentication variables
  examples/eda-setup.yml
  plugins/doc_fragments/eda_controller.py
  plugins/module_utils/arguments.py
  plugins/modules/controller_token.py
  plugins/modules/decision_environment.py
  plugins/modules/decision_environment_info.py
  plugins/modules/project.py
  plugins/modules/project_info.py
  plugins/modules/user.py
  tests/integration/integration_config.yaml.template
  tests/integration/targets/activation/tasks/main.yml
  tests/integration/targets/controller_token/tasks/main.yml
  tests/integration/targets/credential/tasks/main.yml
  tests/integration/targets/credential_type/tasks/main.yml
  tests/integration/targets/decision_environment/tasks/main.yml
  tests/integration/targets/decision_environment_info/tasks/main.yml
  tests/integration/targets/event_stream/tasks/main.yml
  tests/integration/targets/project/tasks/main.yml
  tests/integration/targets/project_info/tasks/main.yml
  tests/integration/targets/user/tasks/main.yml
  tests/run-staging
Labels: enhancement

#410 fix: add restart activation AAP-37681
  .gitignore
  plugins/module_utils/client.py
  plugins/module_utils/controller.py
  plugins/modules/rulebook_activation.py
  tests/integration/targets/activation/tasks/activation_lifecycle.yml
  tests/integration/targets/activation/tasks/main.yml
Labels: bug

#414 fix: [AAP-41820] add proxy param for project create module
  plugins/modules/project.py
  tests/integration/targets/project/tasks/create.yml
  tests/integration/targets/project/tasks/main.yml
  tests/run-staging
Labels: bug

#415 chore: remove unnecessary 'type' keyword from variables
  plugins/modules/controller_token.py
  plugins/modules/event_stream.py
  plugins/modules/project.py
Labels: skip-changelog

#409 feat [AAP-40577]: add support for edit activations
  plugins/modules/rulebook_activation.py
  tests/integration/targets/activation/tasks/main.yml
Labels: enhancement, feature

#416 Move Activation Copy to Separate Module-AAP-42215
  .config/dictionary.txt
  .config/manifest.txt
  meta/runtime.yml
  plugins/module_utils/controller.py
  plugins/modules/rulebook_activation.py
  plugins/modules/rulebook_activation_copy.py
  tests/integration/targets/activation/tasks/main.yml
Labels: bug

#418 chore: release 2.6.1
  galaxy.yml
Labels: skip-changelog
